//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yumi1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yumi1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST_TYPE=PfsGetItemInfo
        ///DATABASE=
        ///USER_ID =
        ///PASSWORD =
        ///SERIAL_NUM=
        ///RETURN_VALUES=COMP_ITEM_NUMBER;COMP_ITEM_DESC.
        /// </summary>
        public static string PfsGetItemInfo {
            get {
                return ResourceManager.GetString("PfsGetItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST_TYPE=PfsQuery
        ///DATABASE=
        ///USER_ID=
        ///PASSWORD=
        ///ITEM_NUM=
        ///OPERATION_CODE=
        ///SERIAL_NUM=.
        /// </summary>
        public static string PfsQuery {
            get {
                return ResourceManager.GetString("PfsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST_TYPE=PfsSendResults
        ///DATABASE=
        ///USER_ID=
        ///PASSWORD=
        ///ITEM_NUM=
        ///OPERATION_CODE=
        ///SERIAL_NUM=
        ///PASS_FAIL=.
        /// </summary>
        public static string PfsSendResults {
            get {
                return ResourceManager.GetString("PfsSendResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST_TYPE=PfsSendSignOff
        ///DATABASE=
        ///USER_ID=
        ///PASSWORD=
        ///PRODUCTION_ORDER=
        ///SERIAL_NUM=
        ///OPERATION_CODE=.
        /// </summary>
        public static string PfsSendSignOff {
            get {
                return ResourceManager.GetString("PfsSendSignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST_TYPE=PfsVerifyUserInput
        ///DATABASE=
        ///USER_ID=
        ///PASSWORD=.
        /// </summary>
        public static string PfsVerifyUserInput {
            get {
                return ResourceManager.GetString("PfsVerifyUserInput", resourceCulture);
            }
        }
    }
}
